### ISSUE TITLE
Handle SQL Insert Exceptions

### ISSUE THREAD

**Issue by mbasa-geolonia** [ichnion/excavator#13]
In other languages there is a try..catch..finally to handle exceptions and continue on with the process. Is there an equivalent in Rust so that SQL exceptions can be caught without the application stopping.

**Comment by chansuke** [comment]
@mbasa-georepublic Thank you for your comment and sorry for the late reply.  `Result<T, E>` handles exceptions in other languages and I'd like to work on this.
https://doc.rust-lang.org/book/ch09-02-recoverable-errors-with-result.html
