### ISSUE TITLE
Create installable binaries for releases

### ISSUE THREAD

**Issue by dkastl** [ichnion/excavator#55]
Let's research about a way to create installable binaries for  

- [ ] Windows
- [ ] MacOS
- [ ] Linux

**Comment by dkastl** [comment]
We can use GH Actions to automate this:

- https://alican.codes/rust-github-actions
- https://github.com/actions-rs/toolchain

**Comment by GawenMonnot** [comment]
Actually, by typing "cargo install excavator" we already do it. Do you want to find an alternative to make it easier for every customers (even the ones who don't know how to use a terminal) to install excavator? If this is your purpose, I can add more documentation and I think that it would be enough, as it is not that hard to install excavator using a terminal.

**Comment by dkastl** [comment]
But then you have to install `cargo`. Can't we build `.exe` or `.msi` installers?

**Comment by GawenMonnot** [comment]
You are right, I didn't think about Cargo. I will look if we can build an installer, but one of my concern is about updating the tool. Because updating is easy if you install it with the "Cargo way". I will think about it.

**Comment by dkastl** [comment]
Look at the GH Actions links before. We can all automate this, by building executable when making a new release on Github, when pushing changes, etc.

In another project for example, I made a build with every push and pull request, just to test, if it works. And a release tag triggered the builds to be linked and preserved with the release notes: https://github.com/ursci/hikagefinder-app/tree/master/.github/workflows

**Comment by dkastl** [comment]
When you look at some release, you see the Android APK attached: https://github.com/ursci/hikagefinder-app/releases/tag/v1.0.1
